/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Robotics Education Platform",
  "tagline": "Learn Robotics with ROS 2 and AI Integration",
  "favicon": "img/favicon.ico",
  "url": "https://your-docusaurus-test-site.com",
  "baseUrl": "/",
  "organizationName": "your-github-username",
  "projectName": "robotics-education-platform",
  "onBrokenLinks": "throw",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\dell\\OneDrive\\Desktop\\hackathon-1\\sidebars.js",
          "editUrl": "https://github.com/your-github-username/robotics-education-platform/edit/main/",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "routeBasePath": "/docs"
        },
        "blog": false,
        "theme": {
          "customCss": "C:\\Users\\dell\\OneDrive\\Desktop\\hackathon-1\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "Robotics Education",
      "logo": {
        "alt": "Robotics Logo",
        "src": "img/docusaurus-logo-png.png",
        "width": 32,
        "height": 32
      },
      "hideOnScroll": false,
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "docs",
          "position": "left",
          "label": "Modules"
        },
        {
          "type": "dropdown",
          "label": "Resources",
          "position": "left",
          "items": [
            {
              "label": "Code Examples",
              "to": "/docs/code-examples/"
            },
            {
              "label": "AI Robot Control",
              "to": "/docs/ai-robot-control/"
            }
          ]
        },
        {
          "href": "https://github.com/your-github-username/robotics-education-platform",
          "label": "GitHub",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Start Learning",
          "items": [
            {
              "label": "ROS 2 Introduction",
              "to": "/docs/ros2-basics/introduction"
            },
            {
              "label": "Setup Guide",
              "to": "/docs/ros2-basics/setup"
            },
            {
              "label": "Tutorials",
              "to": "/docs/ros2-basics/examples/publisher-tutorial"
            }
          ]
        },
        {
          "title": "Advanced Topics",
          "items": [
            {
              "label": "Digital Twin",
              "to": "/docs/digital-twin/"
            },
            {
              "label": "AI Robot Brain",
              "to": "/docs/ai-robot-brain/"
            },
            {
              "label": "Vision-Language-Action",
              "to": "/docs/vision-language-action/"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/your-github-username/robotics-education-platform"
            },
            {
              "label": "Discussions",
              "href": "https://github.com/your-github-username/robotics-education-platform/discussions"
            },
            {
              "label": "Issues",
              "href": "https://github.com/your-github-username/robotics-education-platform/issues"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Robotics Education Platform. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "python",
        "bash",
        "json",
        "yaml",
        "docker",
        "cmake"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 5
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "robotics, ROS 2, AI, digital twin, simulation, Gazebo, Unity, NVIDIA Isaac, VLA, humanoid robots"
      },
      {
        "name": "description",
        "content": "Comprehensive robotics education platform covering ROS 2, AI integration, digital twins, and advanced robot control."
      },
      {
        "name": "author",
        "content": "Robotics Education Platform"
      },
      {
        "name": "robots",
        "content": "index, follow"
      }
    ],
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    }
  },
  "plugins": [],
  "clientModules": [],
  "stylesheets": [],
  "scripts": [],
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "headTags": [],
  "titleDelimiter": "|",
  "noIndex": false
};
